modLoader = "javafml"
loaderVersion = "[46,)"
license = "$license"

[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
logoFile = "icon.png"
authors = "$author, unilock"
description = "$description"

[[dependencies.yep]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.yep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "SERVER"
